name: .NET 6 CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: [self-hosted, runner1]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: dotnet restore
      run: dotnet restore > restore.log 2>&1

    - name: dotnet build
      run: dotnet build > build.log 2>&1
    
    - name: dotnet publish
      run: dotnet publish > publish.log 2>&1

    - name: Analyze Pipeline Logs
      if: always()
      uses: ./github/actions/log-analyzer

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-webapi-artifacts
        path: ./publish
